### PR TITLE
Adjusted CSS for career exploration page

### PR DESCRIPTION
**Pull request by skcain**
Moved CSS to a new file

### CODE REVIEW

**Comment by skcain** [comment]
Still to be addressed:
- Working counter for the results number @ the top
- The training icon shows up dynamically, it would be great if we can show the rest dynamically as well.
- Only show one career at a time, create a new page that lists all the careers and allows for print.

**Comment by antislice** [comment]
The training icon showing up dynamically is because `training_money_available` is in the datamodel. I added a `certification_required` you could use, but the other ones would have to be added.

Good to keep in mind that for all the extra pieces of info that we want to show, someone is going to have to research and/or compile, and right now there's a fair amount stuff we have to put together already.

**Comment by skcain** [comment]
@antislice: Maybe for now we just do those two then.

**Comment by antislice** [comment]
:ship:

**Pull request merged**
